<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MusicShopWebAPI">
      <HintPath>..\MusicShopWebAPI\bin\Debug\netcoreapp3.1\MusicShopWebAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
